version: '3.8'
services:
  db:
    image: arm64v8/mysql:8.0
    platform: linux/arm64/v8
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure:10
    environment:
      MYSQL_ROOT_PASSWORD: rs123
      MYSQL_DATABASE: wordpress
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-fpm-alpine
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    links:
      - db
    
volumes:
  db_data:
