name: Deploy to Azure Web App 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{ "clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}" }'

      - name: ACR Login
        uses: azure/acr-login@65c1ef99a66549505822715a4eefb09995c3c594
        with:
          acr: ${{ secrets.ACR_NAME }}

      - name: Build and Push Image
        run: |
          docker build -t $ACR_NAME/${{ secrets.IMAGE_NAME }} .
          docker push $ACR_NAME/${{ secrets.IMAGE_NAME }}
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: bms-bkend
          images: ${{ secrets.ACR_NAME }}/${{ secrets.IMAGE_NAME }}

env:
  AZURE_WEBAPP_NAME: bms-bkend
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Please adjust to your application, relative to the repository root
  NODE_VERSION: '16.x'       # Please adjust to your node version
